FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

# Copia arquivos de configuração
COPY pom.xml .
COPY src ./src

# Instala dependências
RUN mvn dependency:go-offline

# Porta
EXPOSE 8081

# Roda em modo dev com DevTools
CMD ["mvn", "spring-boot:run"]
